version: '3.8'
services:
  php:
    build: .
    container_name: my-php
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - mynet

  db:
    image: postgres:latest
    container_name: my-postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - mynet

networks:
  mynet:

volumes:
  db-data:
